splash = false
ipc = on

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/steel_haze_wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/steel_haze_2560x1440.jpg
    fit_mode = cover
}

