splash = false
ipc = on

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wp-metal.png
    fit_mode = fill
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/wp-metal.png
    fit_mode = fill
}

